In [6]:
x = [2,4,6]
y = [3,5,6]

[5, 9, 12]


In [ ]:
#mi manera
z = []
for i in range(0,len(x)):
    z.append(x[i]+y[i])
print(z)

In [7]:
#manera del profe
z =[]
for xi, yi in zip(x,y):
    z.append(xi+yi)
z

[5, 9, 12]

In [9]:
#manera profe dos
[xi+yi for xi,yi in zip(x,y)] #list Comprehension

[5, 9, 12]

In [11]:
[xi**2 for xi in x]

[4, 16, 36]

In [15]:
import numpy as np

In [18]:
x = np.array([2,1,3])
y = np.array([4,6,7])
print(x+y)
print(type(x))

[ 6  7 10]
<class 'numpy.ndarray'>


In [20]:
lista = [2,4,5,6]
print(lista*5)
print(x*5)

[2, 4, 5, 6, 2, 4, 5, 6, 2, 4, 5, 6, 2, 4, 5, 6, 2, 4, 5, 6]
[10  5 15]


In [26]:
#Formas de hacer producto punto
np.sum(x*y),x.dot(y),y.dot(x),x@y,(x*y).sum()

(35, 35, 35, 35, 35)

In [28]:
#calcular la normal de un vector
np.linalg.norm(x)

3.7416573867739413

In [30]:
np.sqrt(x@x),(x@x)**.5

(3.7416573867739413, 3.7416573867739413)

In [33]:
#Matrices
A = np.array([ [1,3,2],[1,0,0],[1,2,2] ])

B = np.array([[1,0,5],
             [7,5,0],
             [2,1,1]])
print(A)
print(B)

[[1 3 2]
 [1 0 0]
 [1 2 2]]
[[1 0 5]
 [7 5 0]
 [2 1 1]]


In [40]:
#suma de las matrices
A + B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

In [42]:
A@B

array([[26, 17,  7],
       [ 1,  0,  5],
       [19, 12,  7]])

In [43]:
B@A

array([[ 6, 13, 12],
       [12, 21, 14],
       [ 4,  8,  6]])

In [44]:
#ver dimension de matriz
A.shape

(3, 3)

In [46]:
#tamaño de los elementos de la matriz
A.size

9

In [52]:
A = np.arange(1,10)
print(A,A.shape)
print(np.arange(1,10).reshape(3,3))

[1 2 3 4 5 6 7 8 9] (9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
A = np.arange(1,13).reshape(3,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
B = np.arange(8).reshape(4,2)
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [65]:
#matriz identidad
I = np.eye(2,2)
I

array([[1., 0.],
       [0., 1.]])

In [69]:
#actividad Sistema de ecuaciones lineales
A = np.matrix([ [1,-2],[3,2] ])
b = np.matrix([ [1],[11] ])

x = (A**-1)*b
x

matrix([[3.],
        [1.]])

In [78]:
#ejercicio
A = np.matrix([ [1,2,3],[2,5,2],[6,-3,1] ])
b = np.matrix([ [6],[4],[2] ])

x = (A**-1)*b
print(x,"\n")
x = np.linalg.solve(A,b)
print(x,"\n")
print(A*x)

[[5.55111512e-17]
 [4.16333634e-17]
 [2.00000000e+00]] 

[[0.]
 [0.]
 [2.]] 

[[6.]
 [4.]
 [2.]]


In [81]:
#actividad
A = np.matrix([ [3,2,4],[5,3,2],[6,6,6] ])
b = np.matrix([ [206],[210],[412] ])

x = np.linalg.solve(A,b)
x

matrix([[15.33333333],
        [26.66666667],
        [26.66666667]])

In [82]:
#actividad dos
A = np.matrix([ [3,2,1],[2,1,1],[1,1,1] ])
b = np.matrix([ [130],[90],[60] ])

x = np.linalg.solve(A,b)
x

matrix([[30.],
        [10.],
        [20.]])